server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_mvc
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: validate